/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'NVM_RevB+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32u5xx.h"

/* Keil::Device:Startup&Source ASM@1.3.0 */
#define RTE_DEVICE_STARTUP_STM32U5XX    /* Device Startup for STM32U5 */


#endif /* RTE_COMPONENTS_H */
